title: Devi Priya
logo: /images/circle_shot.png
description: | # your text below (remove <br> elements if you don't need line breaks)
  Product Manager turned Builder and GenAI enthusiast. Masterâ€™s degree in Information Technology Management from the University of Texas at Dallas. Previously at Microsoft and Deloitte.
  <a href="https://www.linkedin.com/in/devipriyak/">View my LinkedIn Profile</a>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
theme: jekyll-theme-minimal





